### ISSUE TITLE
Order of arguments

### ISSUE THREAD

**Issue by emilbayes** [sindresorhus/math-clamp#1]
How come you chose the value to be clamped as the first argument? It makes it hard to curry the function for easy reuse.

**Comment by sindresorhus** [comment]
I don't make APIs based on how easy they can be curried. I prefer to keep the main input as the first argument. This is how most JS APIs are designed. If you curry a lot, you can use the Lodash `_.rearg` method. I do wish we had a native method like bind that could bind in the reverse order or the last parameter though. Would make currying a lot more feasible.
